#!/usr/bin/env php
<?php
/**
 * Copyright © OXID eSales AG. All rights reserved.
 * See LICENSE file for license details.
 */

$installationRootPath = dirname(dirname(dirname(dirname(__FILE__))));
$vendorPath = $installationRootPath . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR;

require_once $vendorPath . 'autoload.php';

try {

    $helpFactory = new \OxidEsales\EshopIdeHelper\HelpFactory();
    $generator = $helpFactory->getGenerator();
    $generator->generate();

} catch (\Exception $exception) {
    $message = $exception->getMessage();
    $code = $exception->getCode();
    $traceString = $exception->getTraceAsString();

    echo $message . PHP_EOL;
    echo "error code: $code" . PHP_EOL;
    echo "stack trace:" . PHP_EOL;
    echo $traceString . PHP_EOL;
    exit(1);
}
exit(0);
