#!/usr/bin/env php
<?php

/**
 * Copyright © OXID eSales AG. All rights reserved.
 * See LICENSE file for license details.
 */

declare(strict_types=1);

use OxidEsales\EshopIdeHelper\GeneratorFactory;

require_once dirname(__FILE__, 4) . DIRECTORY_SEPARATOR .  'vendor' . DIRECTORY_SEPARATOR .  'autoload.php';

(new GeneratorFactory())->create()->generate();
echo "IDE helper files generated successfully!\n";
exit(0);
